import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {render} from './render.mjs';
import {languages} from './content.mjs';
import {intakeCopy} from './intake-copy.mjs';
import {portalCopy} from './portal-copy.mjs';
import {photos} from './photos.mjs';
import {sourceSite,renderSourcePages} from './source-pages.mjs';
await mkdir('dist',{recursive:true});
const css=await readFile('style.css','utf8')+'\n'+await readFile('intake.css','utf8');
const client='const copy='+JSON.stringify(intakeCopy)+';\n'+await readFile('app-client.js','utf8');
const version=createHash('sha256').update(css+client).digest('hex').slice(0,12);
const pages=Object.fromEntries(Object.keys(languages).map(lang=>['/'+lang+'/',render(lang).replace('/style.css"',`/style.css?v=${version}"`).replace('/app.js"',`/app.js?v=${version}"`)]));
Object.assign(pages,renderSourcePages(pages['/en-IE/']));
const hero=(await readFile('assets/hero.jpg')).toString('base64');
const runtime='const photoSources='+JSON.stringify({...Object.fromEntries(photos.map(p=>['/photos/'+p.id+'.jpg',p.url])),...sourceSite.assets})+';\n'+await readFile('worker-runtime.txt','utf8');
const intake=await readFile('intake-runtime.txt','utf8');
const portalHtml=await readFile('portal.html','utf8'),portalCss=await readFile('portal.css','utf8'),portalClient='const portalCopy='+JSON.stringify(portalCopy)+';\n'+await readFile('portal-client.js','utf8'),portalRuntime=(await readFile('portal-runtime.mjs','utf8')).replace(/^export /gm,'');
await writeFile('dist/worker.mjs',`const pages=${JSON.stringify(pages)};\nconst css=${JSON.stringify(css)};\nconst hero=${JSON.stringify(hero)};\nconst client=${JSON.stringify(client)};\nconst portalHtml=${JSON.stringify(portalHtml)},portalCss=${JSON.stringify(portalCss)},portalClient=${JSON.stringify(portalClient)};\n${portalRuntime}\n${intake}\n${runtime}`);
console.log('Built 5 translated pages and Cloudflare Worker.');
