export const photos=[
{id:'town',label:'Dominick Street',author:'Colin Park',license:'CC BY-SA 2.0',licenseUrl:'https://creativecommons.org/licenses/by-sa/2.0/',source:'https://commons.wikimedia.org/wiki/File:Mullingar_-_View_west_along_Dominick_Street_-_geograph.org.uk_-_7670181.jpg',url:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Mullingar_-_View_west_along_Dominick_Street_-_geograph.org.uk_-_7670181.jpg/960px-Mullingar_-_View_west_along_Dominick_Street_-_geograph.org.uk_-_7670181.jpg'},
{id:'cathedral',label:'Cathedral of Christ the King',author:'JohnArmagh',license:'Public domain',licenseUrl:'https://commons.wikimedia.org/wiki/File:MullingarCathedral.JPG',source:'https://commons.wikimedia.org/wiki/File:MullingarCathedral.JPG',url:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/MullingarCathedral.JPG/960px-MullingarCathedral.JPG'},
{id:'canal',label:'Royal Canal, Mullingar',author:'Colin Park',license:'CC BY-SA 2.0',licenseUrl:'https://creativecommons.org/licenses/by-sa/2.0/',source:'https://commons.wikimedia.org/wiki/File:Mullingar_-_Royal_Canal_N_of_Saunder%27s_Bridge_-_geograph.org.uk_-_4276300.jpg',url:'https://upload.wikimedia.org/wikipedia/commons/d/d2/Mullingar_-_Royal_Canal_N_of_Saunder%27s_Bridge_-_geograph.org.uk_-_4276300.jpg'}
];
const captions={'en-IE':['Our town. Our roots.','Mullingar, County Westmeath','Photography & credits','Photographs cropped for layout. Cropped CC BY-SA photographs remain available under the same licence.'], 'pt-BR':['Nossa cidade. Nossas raízes.','Mullingar, Condado de Westmeath','Fotografias e créditos','Fotografias recortadas para o layout. As imagens CC BY-SA recortadas mantêm a mesma licença.'],pl:['Nasze miasto. Nasze korzenie.','Mullingar, hrabstwo Westmeath','Fotografie i autorzy','Zdjęcia przycięto do układu strony. Zdjęcia CC BY-SA zachowują tę samą licencję.'],ro:['Orașul nostru. Rădăcinile noastre.','Mullingar, comitatul Westmeath','Fotografii și autori','Fotografii decupate pentru pagină. Fotografiile CC BY-SA păstrează aceeași licență.'],uk:['Наше місто. Наше коріння.','Маллінгар, графство Вестміт','Фотографії та автори','Фотографії обрізано для макета. Фотографії CC BY-SA зберігають ту саму ліцензію.']};
export const photo=(id,cls='')=>{const p=photos.find(p=>p.id===id);return `<img class="local-photo ${cls}" src="/photos/${p.id}.jpg" alt="${p.label}, Mullingar" width="1024" height="768" loading="lazy" decoding="async">`;};
export function photoGallery(lang){const c=captions[lang];return `<section id="mullingar" class="local-gallery wrap"><div class="local-heading"><p class="eyebrow">AN MUILEANN gCEARR · WESTMEATH</p><h2>${c[0]}</h2><p>${c[1]}</p></div><div class="local-photos">${photos.map((p,i)=>`<figure>${photo(p.id)}<figcaption><span>0${i+1}</span>${p.label}</figcaption></figure>`).join('')}</div></section>`;}
export function photoCredits(lang){const c=captions[lang];return `<details class="privacy photo-credits"><summary>${c[2]}</summary><p>${c[3]}</p>${photos.map(p=>`<p><a href="${p.source}">${p.label}</a> — ${p.author} · <a href="${p.licenseUrl}">${p.license}</a></p>`).join('')}</details>`;}
