export const photos=[
{id:'town',label:'Dominick Street',author:'Colin Park',license:'CC BY-SA 2.0',licenseUrl:'https://creativecommons.org/licenses/by-sa/2.0/',source:'https://commons.wikimedia.org/wiki/File:Mullingar_-_View_west_along_Dominick_Street_-_geograph.org.uk_-_7670181.jpg',url:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Mullingar_-_View_west_along_Dominick_Street_-_geograph.org.uk_-_7670181.jpg/960px-Mullingar_-_View_west_along_Dominick_Street_-_geograph.org.uk_-_7670181.jpg'},
{id:'cathedral',label:'Cathedral of Christ the King',author:'JohnArmagh',license:'Public domain',licenseUrl:'https://commons.wikimedia.org/wiki/File:MullingarCathedral.JPG',source:'https://commons.wikimedia.org/wiki/File:MullingarCathedral.JPG',url:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/MullingarCathedral.JPG/960px-MullingarCathedral.JPG'},
{id:'canal',label:'Royal Canal, Mullingar',author:'Colin Park',license:'CC BY-SA 2.0',licenseUrl:'https://creativecommons.org/licenses/by-sa/2.0/',source:'https://commons.wikimedia.org/wiki/File:Mullingar_-_Royal_Canal_N_of_Saunder%27s_Bridge_-_geograph.org.uk_-_4276300.jpg',url:'https://upload.wikimedia.org/wikipedia/commons/d/d2/Mullingar_-_Royal_Canal_N_of_Saunder%27s_Bridge_-_geograph.org.uk_-_4276300.jpg'}
];
const stock=[
['property','Property documents and keys','Jakub Żerdzicki','sCV3336RlIw','1759429255330-51145b170dad'],
['documents','Signing documents','Romain Dancre','doplSDELX7E','1603796846097-bee99e4a601f'],
['family','Family outdoors','Mushvig Niftaliyev','Hh4Boy-k5rg','1760633549227-901e0c3cf9d3'],
['workplace','Working together','Scott Graham','5fNmWej4tAA','1454165804606-c3d57bc86b40'],
['justice','Lady Justice sculpture','Tingey Injury Law Firm','L4YGuSg0fxs','1589578527966-fdac0f44566c']
];
photos.push(...stock.map(([id,label,author,source,key])=>({id,label,author,source:'https://unsplash.com/photos/'+source,license:'Unsplash License',licenseUrl:'https://unsplash.com/license',url:'https://images.unsplash.com/photo-'+key+'?w=1000&q=80&fit=max&fm=jpg'})));
photos.push(...[
['commercial','Commercial legal work','2024/02/commercial.webp'],
['notary','Legal reference books','2024/03/books-2.webp'],
['partners','Nooney & Dowdall partners','2024/02/Shane-Johnston-Louis-Kiernan-Matthew-Johnston-Nooney-and-Dowdall-LLP-Solicitors.png'],
['archive','Legal papers and office desk','2024/02/desk-with-paper.png']
].map(([id,label,path])=>({id,label,author:'Nooney & Dowdall LLP website',source:'https://mullingarsolicitors.ie/',license:'Original practice imagery',licenseUrl:'https://mullingarsolicitors.ie/',url:'https://mullingarsolicitors.ie/wp-content/uploads/'+path})));
export function servicePhoto(index){const id=['property','documents','family','workplace','commercial','justice','notary'][index];return `<div class="service-photo"><img src="/photos/${id}.jpg" alt="" width="1000" height="660" loading="lazy" decoding="async"></div>`;}
const captions={'en-IE':['Our town. Our roots.','Mullingar, County Westmeath','Photography & credits','Photographs cropped for layout. Cropped CC BY-SA photographs remain available under the same licence.'], 'pt-BR':['Nossa cidade. Nossas raízes.','Mullingar, Condado de Westmeath','Fotografias e créditos','Fotografias recortadas para o layout. As imagens CC BY-SA recortadas mantêm a mesma licença.'],pl:['Nasze miasto. Nasze korzenie.','Mullingar, hrabstwo Westmeath','Fotografie i autorzy','Zdjęcia przycięto do układu strony. Zdjęcia CC BY-SA zachowują tę samą licencję.'],ro:['Orașul nostru. Rădăcinile noastre.','Mullingar, comitatul Westmeath','Fotografii și autori','Fotografii decupate pentru pagină. Fotografiile CC BY-SA păstrează aceeași licență.'],uk:['Наше місто. Наше коріння.','Маллінгар, графство Вестміт','Фотографії та автори','Фотографії обрізано для макета. Фотографії CC BY-SA зберігають ту саму ліцензію.']};
export const photo=(id,cls='')=>{const p=photos.find(p=>p.id===id);return `<img class="local-photo ${cls}" src="/photos/${p.id}.jpg" alt="${p.label}, Mullingar" width="1024" height="768" loading="lazy" decoding="async">`;};
export function photoGallery(lang){const controls={'en-IE':['Pause slideshow','Play slideshow','Previous photograph','Next photograph'], 'pt-BR':['Pausar painel','Reproduzir painel','Foto anterior','Próxima foto'],pl:['Wstrzymaj pokaz','Odtwórz pokaz','Poprzednie zdjęcie','Następne zdjęcie'],ro:['Oprește prezentarea','Pornește prezentarea','Fotografia anterioară','Fotografia următoare'],uk:['Зупинити показ','Відтворити показ','Попереднє фото','Наступне фото']}[lang];return `<section id="mullingar" class="town-panel" aria-label="Mullingar" data-pause="${controls[0]}" data-play="${controls[1]}"><div class="town-slides" aria-hidden="true">${photos.slice(0,3).map((p,i)=>`<img class="town-slide${i===0?' active':''}" src="/photos/${p.id}.jpg" alt="" width="1024" height="768" loading="lazy" decoding="async">`).join('')}</div><div class="town-shade"></div><div class="town-panel-content wrap"><div><p class="eyebrow">NOONEY &amp; DOWDALL · EST. 1877</p><p class="town-signature">Mullingar</p><span class="town-subtitle">AN MUILEANN gCEARR · COUNTY WESTMEATH</span></div><div class="town-controls"><button id="town-prev" aria-label="${controls[2]}">←</button><span id="town-count">01 / 03</span><button id="town-next" aria-label="${controls[3]}">→</button><button id="town-pause">${controls[0]}</button></div></div></section>`;}
export function photoCredits(lang){const c=captions[lang];return `<details class="privacy photo-credits"><summary>${c[2]}</summary><p>${c[3]}</p>${photos.map(p=>`<p><a href="${p.source}">${p.label}</a> — ${p.author} · <a href="${p.licenseUrl}">${p.license}</a></p>`).join('')}</details>`;}

