const pHeaders={'Cache-Control':'no-store, private','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','X-Frame-Options':'DENY','X-Robots-Tag':'noindex, nofollow'};
const pJson=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{...pHeaders,'Content-Type':'application/json;charset=utf-8',...headers}});
const pNow=()=>Math.floor(Date.now()/1000),pId=()=>crypto.randomUUID();
const pHex=buf=>Array.from(new Uint8Array(buf),x=>x.toString(16).padStart(2,'0')).join('');
const pUnhex=s=>Uint8Array.from(s.match(/.{2}/g)||[],x=>parseInt(x,16));
const pRandom=()=>pHex(crypto.getRandomValues(new Uint8Array(32)));
const pHash=async s=>pHex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)));
class PortalError extends Error{constructor(code,status=400){super(code);this.status=status;}}
function pFail(code,status=400){throw new PortalError(code,status);}
function pText(v,max=200){if(typeof v!=='string'||!v.trim()||v.length>max)pFail('invalid_input');return v.trim();}
function pEmail(v){const e=pText(v,180).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e))pFail('invalid_email');return e;}
function pEqual(a,b){if(typeof a!=='string'||typeof b!=='string'||a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0;}
async function pBytes(request,limit=32000){const reader=request.body?.getReader();if(!reader)pFail('empty_body');let total=0;const chunks=[];for(;;){const {done,value}=await reader.read();if(done)break;total+=value.byteLength;if(total>limit){await reader.cancel();pFail('file_too_large',413);}chunks.push(value);}const bytes=new Uint8Array(total);let at=0;for(const chunk of chunks){bytes.set(chunk,at);at+=chunk.length;}return bytes;}
async function pBody(request){if(!request.headers.get('Content-Type')?.startsWith('application/json'))pFail('json_required',415);try{return JSON.parse(new TextDecoder().decode(await pBytes(request)));}catch(e){if(e instanceof PortalError)throw e;pFail('invalid_json');}}
async function pPassword(password,salt,pepper){if(typeof password!=='string'||password.length<12||password.length>128)pFail('password_length');if(!pepper)pFail('not_configured',503);const hmac=await crypto.subtle.importKey('raw',new TextEncoder().encode(pepper),{name:'HMAC',hash:'SHA-256'},false,['sign']);const pre=await crypto.subtle.sign('HMAC',hmac,new TextEncoder().encode(password));const key=await crypto.subtle.importKey('raw',pre,'PBKDF2',false,['deriveBits']);return pHex(await crypto.subtle.deriveBits({name:'PBKDF2',salt:pUnhex(salt),iterations:100000,hash:'SHA-256'},key,256));}
async function pAudit(db,user,action,target){await db.prepare('INSERT INTO portal_audit VALUES(?,?,?,?,?)').bind(pId(),user,action,target,pNow()).run();}
async function pUser(request,db){const token=request.headers.get('Cookie')?.match(/(?:^|;\s*)__Host-nd_session=([a-f0-9]{64})(?:;|$)/)?.[1];if(!token)return null;return db.prepare('SELECT u.id,u.email,u.name,u.role FROM portal_users u JOIN portal_sessions s ON s.user_id=u.id WHERE s.token_hash=? AND s.expires_at>? AND u.active=1').bind(await pHash(token),pNow()).first();}
const pCookie=token=>`__Host-nd_session=${token}; Path=/; Secure; HttpOnly; SameSite=Strict; Max-Age=28800`;
async function pSession(db,user){const token=pRandom();await db.batch([db.prepare('DELETE FROM portal_sessions WHERE expires_at<?').bind(pNow()),db.prepare('INSERT INTO portal_sessions VALUES(?,?,?)').bind(await pHash(token),user,pNow()+28800)]);return pCookie(token);}
function pAdmin(user){if(user.role!=='admin')pFail('forbidden',403);}
async function pRate(request,env,key='write'){if(!env.PORTAL_LIMIT)pFail('not_configured',503);const result=await env.PORTAL_LIMIT.limit({key:key+':'+(request.headers.get('CF-Connecting-IP')||'unknown')});if(!result.success)pFail('rate_limit',429);}
export function calculateFee(service,quantity){const q=Number(quantity);if(!Number.isFinite(q)||q<=0||q>100||Math.abs(q*100-Math.round(q*100))>0.000001)pFail('invalid_quantity');const units=Math.round(q*100),net=Math.round(service.price_cents*units/100),vat=Math.round(net*service.vat_bps/10000),total=net+vat;if(!Number.isSafeInteger(total)||total>10000000)pFail('amount_limit');return {units,net,vat,total};}
export function dublinTime(input){if(typeof input!=='string'||!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(input))pFail('invalid_date');const target=Date.parse(input+'Z');if(!Number.isFinite(target))pFail('invalid_date');const fmt=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Dublin',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'});const match=d=>{const p=Object.fromEntries(fmt.formatToParts(new Date(d)).map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}`;};const found=[target-3600000,target,target+3600000].filter(t=>match(t)===input);if(found.length!==1)pFail('ambiguous_dublin_time');return new Date(found[0]).toISOString();}
function pMeeting(v){if(!v)return '';const u=new URL(pText(v,1500));if(u.protocol!=='https:'||u.username||u.password||!['meet.google.com','teams.microsoft.com','teams.live.com','zoom.us'].some(h=>u.hostname===h||u.hostname.endsWith('.'+h)))pFail('invalid_meeting_url');return u.href;}
function pMime(bytes){if(bytes.length<12)pFail('file_type');if(new TextDecoder().decode(bytes.slice(0,5))==='%PDF-')return 'application/pdf';if(bytes[0]===255&&bytes[1]===216&&bytes[2]===255)return 'image/jpeg';if(pHex(bytes.slice(0,8))==='89504e470d0a1a0a')return 'image/png';if(new TextDecoder().decode(bytes.slice(0,4))==='RIFF'&&new TextDecoder().decode(bytes.slice(8,12))==='WEBP')return 'image/webp';pFail('file_type');}
async function pVaultKey(env){if(!/^[a-f0-9]{64}$/.test(env.PORTAL_VAULT_KEY||''))pFail('not_configured',503);return crypto.subtle.importKey('raw',pUnhex(env.PORTAL_VAULT_KEY),'AES-GCM',false,['encrypt','decrypt']);}
async function pStoreFile(db,env,user,owner,bytes,name,source){const mime=pMime(bytes);const clean=pText(name,160).replace(/[\x00-\x1f\\/<>"']/g,'_');const id=pId(),iv=crypto.getRandomValues(new Uint8Array(12));const data=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode(id+':'+owner)},await pVaultKey(env),bytes));const statements=[db.prepare('INSERT INTO portal_documents VALUES(?,?,?,?,?,?,?,?,0)').bind(id,owner,clean,mime,bytes.length,pHex(iv),source,pNow())];for(let i=0;i<data.length;i+=131072)statements.push(db.prepare('INSERT INTO portal_chunks VALUES(?,?,?)').bind(id,i/131072,data.slice(i,i+131072).buffer));try{await db.batch(statements);}catch(e){if(String(e).includes('document_quota'))pFail('storage_quota',413);throw e;}await pAudit(db,user.id,'document.upload',id);return pJson({id},201);}
async function pWebhook(request,env){if(!env.STRIPE_WEBHOOK_SECRET)pFail('payments_not_configured',503);const raw=await pBytes(request,128000),header=request.headers.get('Stripe-Signature')||'',parts=header.split(',').map(x=>x.split('=')),stamp=parts.find(x=>x[0]==='t')?.[1],signatures=parts.filter(x=>x[0]==='v1').map(x=>x[1]);if(!/^\d+$/.test(stamp||'')||Math.abs(pNow()-Number(stamp))>300)pFail('invalid_signature',400);const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(env.STRIPE_WEBHOOK_SECRET),{name:'HMAC',hash:'SHA-256'},false,['sign']);const payload=new TextEncoder().encode(stamp+'.'+new TextDecoder().decode(raw));const sig=pHex(await crypto.subtle.sign('HMAC',key,payload));if(!signatures.some(x=>pEqual(x,sig)))pFail('invalid_signature',400);let event;try{event=JSON.parse(new TextDecoder().decode(raw));}catch{pFail('invalid_json');}if(!['checkout.session.completed','checkout.session.async_payment_succeeded'].includes(event.type))return pJson({received:true});const obj=event.data?.object;if(obj?.payment_status!=='paid')return pJson({received:true});const db=env.PORTAL_DB,quote=await db.prepare('SELECT * FROM portal_quotes WHERE id=?').bind(obj.metadata?.quote_id||'').first();if(!quote||obj.amount_total!==quote.total_cents||obj.currency!=='eur'||quote.checkout_id!==obj.id||!['approved','paid'].includes(quote.status))pFail('payment_mismatch',400);await db.batch([db.prepare('INSERT OR IGNORE INTO portal_events VALUES(?,?)').bind(event.id,pNow()),db.prepare("UPDATE portal_quotes SET status='paid',paid_at=COALESCE(paid_at,?) WHERE id=? AND status='approved'").bind(pNow(),quote.id)]);return pJson({received:true});}
export async function portalHandler(request,env,url){
 try{
  const db=env?.PORTAL_DB;if(!db)pFail('not_configured',503);const path=url.pathname.replace('/api/portal','');
  if(path==='/stripe-webhook'){if(request.method!=='POST')pFail('method',405);return await pWebhook(request,env);}
  if(!['GET','POST'].includes(request.method))pFail('method',405);
  if(request.method==='POST'){if(request.headers.get('Origin')!==url.origin)pFail('origin',403);await pRate(request,env,['/login','/activate','/setup'].includes(path)?'auth':'write');}
  if(path==='/config'&&request.method==='GET'){const setup=!(await db.prepare("SELECT id FROM portal_users WHERE role='admin' LIMIT 1").first());return pJson({setupRequired:setup});}
  if(path==='/setup'&&request.method==='POST'){
   const b=await pBody(request);if(!env.PORTAL_SETUP_TOKEN||!pEqual(b.token,env.PORTAL_SETUP_TOKEN))pFail('invalid_access',403);
   if(await db.prepare("SELECT id FROM portal_users WHERE role='admin' LIMIT 1").first())pFail('already_configured',409);
   const salt=pRandom(),hash=await pPassword(b.password,salt,env.PORTAL_PEPPER);
   try{await db.prepare("INSERT INTO portal_users VALUES(?,?,?,'admin',1,?,?,?)").bind('administrator',pEmail(b.email),pText(b.name,100),hash,salt,pNow()).run();}catch{pFail('already_configured',409);}
   await pAudit(db,'administrator','admin.setup','administrator');return pJson({ok:true},200,{'Set-Cookie':await pSession(db,'administrator')});
  }
  if(path==='/activate'&&request.method==='POST'){
   const b=await pBody(request),token=await pHash(pText(b.token,100)),invite=await db.prepare('SELECT i.*,u.email FROM portal_invites i JOIN portal_users u ON u.id=i.user_id WHERE token_hash=? AND claim IS NULL AND expires_at>?').bind(token,pNow()).first();
   if(!invite||invite.email!==pEmail(b.email))pFail('invalid_invitation',403);const salt=pRandom(),hash=await pPassword(b.password,salt,env.PORTAL_PEPPER),claim=pRandom();
   const result=await db.batch([db.prepare('UPDATE portal_invites SET claim=? WHERE token_hash=? AND claim IS NULL AND expires_at>?').bind(claim,token,pNow()),db.prepare('UPDATE portal_users SET password_hash=?,password_salt=?,active=1 WHERE id=? AND EXISTS(SELECT 1 FROM portal_invites WHERE token_hash=? AND claim=?)').bind(hash,salt,invite.user_id,token,claim),db.prepare('DELETE FROM portal_sessions WHERE user_id=? AND EXISTS(SELECT 1 FROM portal_invites WHERE token_hash=? AND claim=?)').bind(invite.user_id,token,claim)]);
   if(!result[0].meta.changes)pFail('invalid_invitation',403);await pAudit(db,invite.user_id,'client.activate',invite.user_id);return pJson({ok:true},200,{'Set-Cookie':await pSession(db,invite.user_id)});
  }
  if(path==='/login'&&request.method==='POST'){
   const b=await pBody(request),email=pEmail(b.email);if(!(await env.PORTAL_LIMIT.limit({key:'email:'+await pHash(email)})).success)pFail('rate_limit',429);
   const row=await db.prepare('SELECT * FROM portal_users WHERE email=?').bind(email).first();const salt=row?.password_salt||'0'.repeat(64);let hash;try{hash=await pPassword(b.password,salt,env.PORTAL_PEPPER);}catch{pFail('invalid_login',401);}if(!row||!row.active||!pEqual(row.password_hash,hash))pFail('invalid_login',401);return pJson({ok:true},200,{'Set-Cookie':await pSession(db,row.id)});
  }
  const user=await pUser(request,db);if(!user)pFail('login_required',401);
  if(path==='/logout'&&request.method==='POST'){const token=request.headers.get('Cookie')?.match(/__Host-nd_session=([a-f0-9]{64})/)?.[1];if(token)await db.prepare('DELETE FROM portal_sessions WHERE token_hash=?').bind(await pHash(token)).run();return pJson({ok:true},200,{'Set-Cookie':'__Host-nd_session=; Path=/; Secure; HttpOnly; SameSite=Strict; Max-Age=0'});}
  if(path==='/me'&&request.method==='GET'){
   const settings=await db.prepare("SELECT value FROM portal_settings WHERE key='integrations'").first();const integration=settings?JSON.parse(settings.value):{};
   return pJson({user,integrations:{googleClientId:integration.googleClientId||'',googleApiKey:integration.googleApiKey||'',googleAppId:integration.googleAppId||'',dropboxAppKey:integration.dropboxAppKey||'',payments:!!(env.STRIPE_SECRET_KEY&&env.STRIPE_WEBHOOK_SECRET)},storage:{maxFile:5242880,quota:26214400}});
  }
  if(path==='/services'&&request.method==='GET')return pJson({services:(await db.prepare('SELECT * FROM portal_services WHERE active=1 ORDER BY name').all()).results});
  if(path==='/quotes'&&request.method==='GET')return pJson({quotes:(await db.prepare('SELECT q.*,u.name AS client_name FROM portal_quotes q JOIN portal_users u ON u.id=q.user_id WHERE (?=1 OR q.user_id=?) ORDER BY q.created_at DESC LIMIT 200').bind(user.role==='admin'?1:0,user.id).all()).results});
  if(path==='/quotes'&&request.method==='POST'){
   const b=await pBody(request),service=await db.prepare('SELECT * FROM portal_services WHERE id=? AND active=1').bind(pText(b.serviceId,80)).first();if(!service)pFail('service_unavailable',404);const fee=calculateFee(service,b.quantity),id=pId();await db.prepare('INSERT INTO portal_quotes(id,user_id,service_name,quantity_hundredths,net_cents,vat_cents,total_cents,created_at) VALUES(?,?,?,?,?,?,?,?)').bind(id,user.id,service.name,fee.units,fee.net,fee.vat,fee.total,pNow()).run();return pJson({id,...fee,status:'requested'},201);
  }
  if(path==='/checkout'&&request.method==='POST'){
   const b=await pBody(request);if(b.acceptedTerms!==true)pFail('accept_cost_notice');const quote=await db.prepare("SELECT * FROM portal_quotes WHERE id=? AND user_id=? AND status='approved'").bind(pText(b.quoteId,80),user.id).first();if(!quote||quote.terms.length<20)pFail('quote_not_approved',409);if(!env.STRIPE_SECRET_KEY||!env.STRIPE_WEBHOOK_SECRET)pFail('payments_not_configured',503);if(quote.total_cents<50)pFail('amount_limit');
   const form=new URLSearchParams({mode:'payment',success_url:url.origin+'/portal/?payment=return',cancel_url:url.origin+'/portal/?payment=cancel','line_items[0][price_data][currency]':'eur','line_items[0][price_data][unit_amount]':String(quote.total_cents),'line_items[0][price_data][product_data][name]':'Legal services â€” '+quote.id.slice(0,8),'line_items[0][quantity]':'1','metadata[quote_id]':quote.id,client_reference_id:quote.id});
   const response=await fetch('https://api.stripe.com/v1/checkout/sessions',{method:'POST',headers:{Authorization:'Bearer '+env.STRIPE_SECRET_KEY,'Content-Type':'application/x-www-form-urlencoded','Idempotency-Key':'nd-quote-'+quote.id},body:form,signal:AbortSignal.timeout(15000)});if(!response.ok)pFail('payment_unavailable',502);const checkout=await response.json();if(typeof checkout.url!=='string'||new URL(checkout.url).hostname!=='checkout.stripe.com')pFail('payment_unavailable',502);
   await db.prepare('UPDATE portal_quotes SET checkout_id=?,checkout_url=? WHERE id=? AND status=\'approved\'').bind(checkout.id,checkout.url,quote.id).run();await pAudit(db,user.id,'payment.checkout',quote.id);return pJson({url:checkout.url});
  }
  if(path==='/slots'&&request.method==='GET')return pJson({slots:(await db.prepare("SELECT s.id,s.starts_at,s.ends_at,s.kind FROM portal_slots s WHERE s.active=1 AND s.starts_at>? AND NOT EXISTS(SELECT 1 FROM portal_appointments a WHERE a.slot_id=s.id AND a.status='confirmed') ORDER BY s.starts_at LIMIT 100").bind(new Date().toISOString()).all()).results});
  if(path==='/appointments'&&request.method==='GET')return pJson({appointments:(await db.prepare('SELECT a.*,s.starts_at,s.ends_at,s.kind,s.meeting_url,u.name AS client_name FROM portal_appointments a JOIN portal_slots s ON a.slot_id=s.id JOIN portal_users u ON u.id=a.user_id WHERE (?=1 OR a.user_id=?) ORDER BY s.starts_at DESC LIMIT 200').bind(user.role==='admin'?1:0,user.id).all()).results});
  if(path==='/appointments'&&request.method==='POST'){
   const b=await pBody(request),id=pId();try{const r=await db.prepare('INSERT INTO portal_appointments(id,slot_id,user_id,created_at) SELECT ?,id,?,? FROM portal_slots WHERE id=? AND active=1 AND starts_at>?').bind(id,user.id,pNow(),pText(b.slotId,80),new Date().toISOString()).run();if(!r.meta.changes)pFail('slot_unavailable',409);}catch(e){if(e instanceof PortalError)throw e;if(String(e).includes('UNIQUE'))pFail('slot_unavailable',409);throw e;}await pAudit(db,user.id,'appointment.book',id);return pJson({id},201);
  }
  if(path==='/appointments/cancel'&&request.method==='POST'){const b=await pBody(request);const r=await db.prepare("UPDATE portal_appointments SET status='cancelled' WHERE id=? AND (user_id=? OR ?=1) AND status='confirmed'").bind(pText(b.id,80),user.id,user.role==='admin'?1:0).run();if(!r.meta.changes)pFail('not_found',404);await pAudit(db,user.id,'appointment.cancel',b.id);return pJson({ok:true});}
  if(path==='/documents'&&request.method==='GET')return pJson({documents:(await db.prepare('SELECT d.id,d.user_id,d.name,d.mime,d.size,d.source,d.created_at,u.name AS client_name FROM portal_documents d JOIN portal_users u ON u.id=d.user_id WHERE d.removed=0 AND (?=1 OR d.user_id=?) ORDER BY d.created_at DESC LIMIT 300').bind(user.role==='admin'?1:0,user.id).all()).results});
  if(path==='/documents'&&request.method==='POST'){
   let owner=user.id;const assigned=request.headers.get('X-Client-Id');if(assigned){pAdmin(user);const row=await db.prepare("SELECT id FROM portal_users WHERE id=? AND role='client'").bind(assigned).first();if(!row)pFail('not_found',404);owner=row.id;}
   const bytes=await pBytes(request,5242880);let name;try{name=decodeURIComponent(request.headers.get('X-File-Name')||'document.pdf');}catch{pFail('invalid_input');}
   const source=['local','camera','google-drive','dropbox'].includes(request.headers.get('X-File-Source'))?request.headers.get('X-File-Source'):'local';return await pStoreFile(db,env,user,owner,bytes,name,source);
  }
  if(path.startsWith('/documents/')&&request.method==='GET'){
   const id=path.slice('/documents/'.length),doc=await db.prepare('SELECT * FROM portal_documents WHERE id=? AND removed=0 AND (?=1 OR user_id=?)').bind(id,user.role==='admin'?1:0,user.id).first();if(!doc)pFail('not_found',404);const {results}=await db.prepare('SELECT payload FROM portal_chunks WHERE document_id=? ORDER BY part').bind(id).all();const data=new Uint8Array(doc.size+16);let offset=0;for(const r of results){const bytes=r.payload instanceof ArrayBuffer?new Uint8Array(r.payload):new Uint8Array(r.payload);data.set(bytes,offset);offset+=bytes.length;}if(offset!==data.length)pFail('file_unavailable',503);const decrypted=await crypto.subtle.decrypt({name:'AES-GCM',iv:pUnhex(doc.iv),additionalData:new TextEncoder().encode(doc.id+':'+doc.user_id)},await pVaultKey(env),data);await pAudit(db,user.id,'document.download',id);return new Response(decrypted,{headers:{...pHeaders,'Content-Type':doc.mime,'Content-Disposition':`attachment; filename="document.${doc.mime==='application/pdf'?'pdf':doc.mime.split('/')[1]}"; filename*=UTF-8''${encodeURIComponent(doc.name)}`,'Content-Security-Policy':"sandbox; default-src 'none'"}});
  }
  if(path==='/documents/remove'&&request.method==='POST'){const b=await pBody(request),doc=await db.prepare('SELECT id FROM portal_documents WHERE id=? AND removed=0 AND (?=1 OR user_id=?)').bind(pText(b.id,80),user.role==='admin'?1:0,user.id).first();if(!doc)pFail('not_found',404);await db.batch([db.prepare('DELETE FROM portal_chunks WHERE document_id=?').bind(doc.id),db.prepare('UPDATE portal_documents SET removed=1 WHERE id=?').bind(doc.id)]);await pAudit(db,user.id,'document.remove',doc.id);return pJson({ok:true});}
  if(path.startsWith('/admin/')){
   pAdmin(user);
   if(path==='/admin/clients'&&request.method==='GET')return pJson({clients:(await db.prepare("SELECT id,email,name,active FROM portal_users WHERE role='client' ORDER BY name").all()).results});
   if(path==='/admin/invite'&&request.method==='POST'){
    const b=await pBody(request),email=pEmail(b.email),existing=await db.prepare('SELECT id,role FROM portal_users WHERE email=?').bind(email).first();if(existing?.role==='admin')pFail('admin_account');const id=existing?.id||pId(),token=pRandom(),expiry=pNow()+172800;const statements=[];
    if(!existing)statements.push(db.prepare("INSERT INTO portal_users(id,email,name,role,created_at) VALUES(?,?,?,'client',?)").bind(id,email,pText(b.name,100),pNow()));statements.push(db.prepare('DELETE FROM portal_invites WHERE user_id=?').bind(id),db.prepare('INSERT INTO portal_invites(token_hash,user_id,expires_at) VALUES(?,?,?)').bind(await pHash(token),id,expiry));await db.batch(statements);await pAudit(db,user.id,'client.invite',id);return pJson({url:url.origin+'/portal/#invite='+token,expiresAt:expiry,email});
   }
   if(path==='/admin/revoke'&&request.method==='POST'){const b=await pBody(request);await db.batch([db.prepare("UPDATE portal_users SET active=0 WHERE id=? AND role='client'").bind(pText(b.id,80)),db.prepare("DELETE FROM portal_sessions WHERE user_id=? AND user_id IN(SELECT id FROM portal_users WHERE role='client')").bind(b.id),db.prepare('DELETE FROM portal_invites WHERE user_id=?').bind(b.id)]);await pAudit(db,user.id,'client.revoke',b.id);return pJson({ok:true});}
   if(path==='/admin/services'&&request.method==='POST'){const b=await pBody(request),price=Number(b.priceCents),vat=Number(b.vatBps);if(!Number.isInteger(price)||price<0||price>10000000||!Number.isInteger(vat)||vat<0||vat>10000)pFail('invalid_amount');const id=b.id?pText(b.id,80):pId();await db.prepare('INSERT INTO portal_services VALUES(?,?,?,?,?,1) ON CONFLICT(id) DO UPDATE SET name=excluded.name,unit=excluded.unit,price_cents=excluded.price_cents,vat_bps=excluded.vat_bps,active=1').bind(id,pText(b.name,100),pText(b.unit,30),price,vat).run();await pAudit(db,user.id,'service.save',id);return pJson({id});}
   if(path==='/admin/approve-quote'&&request.method==='POST'){const b=await pBody(request),terms=pText(b.terms,10000);if(terms.length<20)pFail('cost_notice_required');const r=await db.prepare("UPDATE portal_quotes SET status='approved',terms=? WHERE id=? AND status='requested'").bind(terms,pText(b.id,80)).run();if(!r.meta.changes)pFail('not_found',404);await pAudit(db,user.id,'quote.approve',b.id);return pJson({ok:true});}
   if(path==='/admin/slots'&&request.method==='POST'){const b=await pBody(request),start=dublinTime(b.start),end=dublinTime(b.end);if(start<=new Date().toISOString()||end<=start||Date.parse(end)-Date.parse(start)>14400000||!['office','video','phone'].includes(b.kind))pFail('invalid_date');const overlap=await db.prepare('SELECT id FROM portal_slots WHERE active=1 AND starts_at<? AND ends_at>?').bind(end,start).first();if(overlap)pFail('slot_overlap',409);const id=pId();try{await db.prepare('INSERT INTO portal_slots VALUES(?,?,?,?,?,1)').bind(id,start,end,b.kind,pMeeting(b.meetingUrl)).run();}catch(e){if(String(e).includes('UNIQUE'))pFail('slot_overlap',409);throw e;}await pAudit(db,user.id,'slot.create',id);return pJson({id});}
   if(path==='/admin/settings'&&request.method==='POST'){const b=await pBody(request),out={};for(const key of ['googleClientId','googleApiKey','googleAppId','dropboxAppKey']){const value=b[key]||'';if(typeof value!=='string'||value.length>220||!/^[-A-Za-z0-9._]*$/.test(value))pFail('invalid_input');out[key]=value;}await db.prepare("INSERT INTO portal_settings VALUES('integrations',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(JSON.stringify(out)).run();await pAudit(db,user.id,'integrations.save','public-app-identifiers');return pJson({ok:true});}
   if(path==='/admin/audit'&&request.method==='GET')return pJson({events:(await db.prepare('SELECT * FROM portal_audit ORDER BY created_at DESC LIMIT 50').all()).results});
  }
  pFail('not_found',404);
 }catch(e){return pJson({error:e instanceof PortalError?e.message:'service_unavailable'},e instanceof PortalError?e.status:503);}
}
