import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {createHmac} from 'node:crypto';
import {portalHandler,calculateFee,dublinTime} from './portal-runtime.mjs';
export function fixture(){const sqlite=new DatabaseSync(':memory:');sqlite.exec(readFileSync(new URL('./portal-schema.sql',import.meta.url),'utf8'));const db={prepare(sql){let values=[];return {bind(...v){values=v.map(x=>x instanceof ArrayBuffer?new Uint8Array(x):x);return this;},async first(){return sqlite.prepare(sql).get(...values)||null;},async all(){return {results:sqlite.prepare(sql).all(...values)};},async run(){return {meta:{changes:sqlite.prepare(sql).run(...values).changes}};}};},async batch(statements){sqlite.exec('BEGIN');try{const out=[];for(const s of statements)out.push(await s.run());sqlite.exec('COMMIT');return out;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};const env={PORTAL_DB:db,PORTAL_LIMIT:{limit:async()=>({success:true})},PORTAL_SETUP_TOKEN:'a'.repeat(64),PORTAL_PEPPER:'b'.repeat(64),PORTAL_VAULT_KEY:'c'.repeat(64)};async function call(path,body,cookie='',headers={}){const url=new URL('https://portal.test/api/portal'+path),raw=body instanceof Uint8Array;return portalHandler(new Request(url,{method:body===undefined?'GET':'POST',headers:{Origin:url.origin,Cookie:cookie,'Content-Type':raw?'application/octet-stream':'application/json',...headers},body:body===undefined?undefined:raw?body:JSON.stringify(body)}),env,url);}return {sqlite,env,call};}
const cookie=r=>r.headers.get('Set-Cookie').split(';')[0];
test('integer fee calculations and Dublin DST conversion',()=>{assert.deepEqual(calculateFee({price_cents:9999,vat_bps:2300},1.5),{units:150,net:14999,vat:3450,total:18449});assert.throws(()=>calculateFee({price_cents:100,vat_bps:0},.001));assert.equal(dublinTime('2027-07-01T10:00'),'2027-07-01T09:00:00.000Z');assert.equal(dublinTime('2027-01-01T10:00'),'2027-01-01T10:00:00.000Z');assert.throws(()=>dublinTime('2027-03-28T01:30'));assert.throws(()=>dublinTime('2027-10-31T01:30'));});
test('portal authorisation, encrypted storage, costs and scheduling operate against SQLite',async()=>{const {sqlite,env,call}=fixture();assert.equal((await call('/documents')).status,401);assert.equal((await call('/setup',{token:'bad'})).status,403);const adminResponse=await call('/setup',{token:env.PORTAL_SETUP_TOKEN,email:'admin@example.test',name:'Test admin',password:'a strong test password'});assert.equal(adminResponse.status,200);const admin=cookie(adminResponse);assert.equal((await call('/setup',{token:env.PORTAL_SETUP_TOKEN})).status,409);
const clients=[];for(const name of ['alice','bob']){const r=await call('/admin/invite',{email:name+'@example.test',name},admin),inv=await r.json(),token=new URL(inv.url).hash.slice(8),credentials={token,email:name+'@example.test',password:'a strong test password'};const activation=await call('/activate',credentials);assert.equal(activation.status,200);assert.equal((await call('/activate',credentials)).status,403);clients.push({cookie:cookie(activation),id:sqlite.prepare('SELECT id FROM portal_users WHERE email=?').get(credentials.email).id});}const [alice,bob]=clients;assert.equal((await call('/admin/clients',undefined,alice.cookie)).status,403);assert.equal((await call('/logout',{},alice.cookie,{Origin:'https://attacker.test'})).status,403);
const bytes=new TextEncoder().encode('%PDF-1.4\nprivate synthetic document\n%%EOF');const upload=await call('/documents',bytes,alice.cookie,{'X-File-Name':'sample.pdf'});assert.equal(upload.status,201);const {id}=await upload.json();const stored=sqlite.prepare('SELECT payload FROM portal_chunks WHERE document_id=?').get(id).payload;assert.ok(!new TextDecoder().decode(stored).includes('private synthetic'));assert.equal((await call('/documents/'+id,undefined,bob.cookie)).status,404);assert.equal((await call('/documents/remove',{id},bob.cookie)).status,404);assert.deepEqual(new Uint8Array(await (await call('/documents/'+id,undefined,alice.cookie)).arrayBuffer()),bytes);assert.equal((await (await call('/documents',undefined,bob.cookie)).json()).documents.length,0);assert.equal((await call('/documents',new Uint8Array(5242881),alice.cookie)).status,413);
const service=await (await call('/admin/services',{name:'Synthetic service',unit:'hour',priceCents:10000,vatBps:2300},admin)).json();const quote=await (await call('/quotes',{serviceId:service.id,quantity:2,total:1},alice.cookie)).json();assert.equal(quote.total,24600);assert.equal((await call('/checkout',{quoteId:quote.id,acceptedTerms:true},alice.cookie)).status,409);assert.equal((await call('/admin/approve-quote',{id:quote.id,terms:'Synthetic complete costs notice only for testing'},bob.cookie)).status,403);assert.equal((await call('/admin/approve-quote',{id:quote.id,terms:'Synthetic complete costs notice only for testing'},admin)).status,200);assert.equal((await call('/checkout',{quoteId:quote.id,acceptedTerms:true},alice.cookie)).status,503);
const slotBody={start:'2028-07-01T10:00',end:'2028-07-01T11:00',kind:'video',meetingUrl:'https://meet.google.com/abc-defg-hij'};const slot=await (await call('/admin/slots',slotBody,admin)).json();assert.ok(slot.id);assert.equal((await call('/admin/slots',{...slotBody,start:'2028-07-01T10:30'},admin)).status,409);const booked=await call('/appointments',{slotId:slot.id},alice.cookie);assert.equal(booked.status,201);assert.equal((await call('/appointments',{slotId:slot.id},bob.cookie)).status,409);assert.equal((await (await call('/appointments',undefined,bob.cookie)).json()).appointments.length,0);assert.equal((await call('/appointments/cancel',{id:(await booked.json()).id},bob.cookie)).status,404);
env.STRIPE_WEBHOOK_SECRET='test_webhook_secret';sqlite.prepare('UPDATE portal_quotes SET checkout_id=? WHERE id=?').run('cs_test',quote.id);const event={id:'evt_test',type:'checkout.session.completed',data:{object:{id:'cs_test',metadata:{quote_id:quote.id},amount_total:24600,currency:'eur',payment_status:'paid'}}};const timestamp=Math.floor(Date.now()/1000),signature=body=>'t='+timestamp+',v1='+createHmac('sha256',env.STRIPE_WEBHOOK_SECRET).update(timestamp+'.'+JSON.stringify(body)).digest('hex');assert.equal((await call('/stripe-webhook',event,'',{'Stripe-Signature':'t=1,v1=bad'})).status,400);const tampered=structuredClone(event);tampered.data.object.amount_total=1;assert.equal((await call('/stripe-webhook',tampered,'',{'Stripe-Signature':signature(tampered)})).status,400);assert.equal((await call('/stripe-webhook',event,'',{'Stripe-Signature':signature(event)})).status,200);assert.equal(sqlite.prepare('SELECT status FROM portal_quotes WHERE id=?').get(quote.id).status,'paid');assert.equal((await call('/stripe-webhook',event,'',{'Stripe-Signature':signature(event)})).status,200);assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM portal_events').get().n,1);
assert.equal((await call('/admin/revoke',{id:alice.id},admin)).status,200);assert.equal((await call('/me',undefined,alice.cookie)).status,401);sqlite.close();});
