import {illustration,townscape} from './illustrations.mjs';
import {content,languages} from './content.mjs';
import {intakeCopy,intakeMarkup} from './intake-copy.mjs';
import {portalCopy} from './portal-copy.mjs';
const esc = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function render(lang){
 const t=content[lang], c=intakeCopy[lang];
 const ids=['expertise','approach','information','contact'];
 const sources=['https://www.lsra.ie/for-law-professionals/your-legal-costs-duties/','https://www.lsra.ie/for-consumers/advertising-by-lawyers/','https://www.dataprotection.ie/en/dpc-guidance/guidance-cookies-and-other-tracking-technologies'];
 return `<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="description" content="${esc(t.intro)}"><meta name="theme-color" content="#041562"><title>Nooney &amp; Dowdall LLP — ${esc(t.title)}</title><link rel="stylesheet" href="/style.css"><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' fill='%23041562'/%3E%3Ctext x='32' y='45' text-anchor='middle' font-size='44' fill='%23FFFFFF' font-family='Georgia'%3EN%3C/text%3E%3C/svg%3E">${Object.keys(languages).map(l=>`<link rel="alternate" hreflang="${l}" href="/${l}/">`).join('')}<script src="/app.js" defer></script></head><body id="top"><a class="skip" href="#main">${t.skip}</a>
 <div class="proposal"><span>${t.notice}</span><a href="https://mullingarsolicitors.ie/">${t.official} ↗</a></div>
 <header class="wrap"><a class="brand" href="/${lang}/" aria-label="Nooney & Dowdall LLP"><span class="brand-mark">N<span>&</span>D</span><span>Nooney & Dowdall<small>LLP · SOLICITORS</small></span></a><nav aria-label="${t.nav.join(', ')}">${t.nav.map((v,i)=>`<a href="#${ids[i]}">${v}</a>`).join('')}</nav><details class="language"><summary>◎ ${languages[lang].split(' (')[0]} <span>⌄</span></summary><div class="language-list" aria-label="${t.language}">${Object.entries(languages).map(([code,label])=>`<a href="/language?lang=${code}" lang="${code}" hreflang="${code}" ${code===lang?'aria-current="page"':''}>${label}${code===lang?' ✓':''}</a>`).join('')}</div></details></header>
 <main id="main"><section class="hero"><div class="hero-copy"><p class="eyebrow">${t.label}</p><h1>${t.title}</h1><p class="intro">${t.intro}</p><div class="actions"><a class="button gold" href="#contact">${t.cta}<span>↗</span></a><a class="quiet" href="#expertise">${t.explore} <span>↓</span></a></div><div class="hero-bottom"><span>NOONEY & DOWDALL LLP</span><span>EST. 1877</span></div></div><div class="hero-image"><canvas id="bird-canvas" aria-hidden="true"></canvas><button id="motion-toggle" class="motion-toggle" aria-pressed="false" hidden>${c.pause}</button><img src="/hero.png" alt="${t.imageAlt}" width="1536" height="864" fetchpriority="high"><div class="image-caption"><span>MULLINGAR</span><span>53.5259° N &nbsp; 7.3381° W</span></div></div></section>
 <div class="ribbon wrap">${t.ribbon.map((x,i)=>`<span><b>0${i+1}</b> ${x}</span>`).join('')}</div>
 <section id="expertise" class="section wrap"><div class="section-heading"><div><p class="eyebrow">${t.eyebrow}</p><h2>${t.expertise}</h2></div><p>${t.serviceIntro}</p></div><div class="services">${t.services.map(([title,desc],i)=>`<article class="service"><div class="service-art">${illustration(i)}</div><span class="number">0${i+1}</span><h3>${title}</h3><p>${desc}</p><a class="service-link" href="#contact" aria-label="${esc(title+' — '+t.cta)}">↗</a></article>`).join('')}</div></section>
 <section id="approach" class="heritage"><div class="wrap heritage-grid"><div class="heritage-art">${townscape()}<div class="heritage-date">1877<span>MULLINGAR &middot; IRELAND</span></div></div><div><p class="eyebrow">${t.approachLabel}</p><h2>${t.approachTitle}</h2><p>${t.approachText}</p><a class="quiet" href="https://mullingarsolicitors.ie/about-us/">${t.team} ↗</a></div></div></section>
 <section class="section wrap"><p class="eyebrow">${t.processLabel}</p><h2>${t.processTitle}</h2><div class="steps">${t.steps.map(([h,p],i)=>`<article><span class="step-num">0${i+1}</span><h3>${h}</h3><p>${p}</p></article>`).join('')}</div></section>
 <section id="information" class="information"><div class="wrap info-grid"><div><p class="eyebrow">${t.infoLabel}</p><h2>${t.infoTitle}</h2><p class="source-title">${t.sources}</p><div class="sources">${sources.map((s,i)=>`<a href="${s}">${t.sourceLabels[i]} ↗</a>`).join('')}</div></div><div class="faqs">${t.faqs.map(([q,a])=>`<details><summary>${q}<span aria-hidden="true">+</span></summary><p>${a}</p></details>`).join('')}</div></div></section>
 <section class="section wrap"><p class="eyebrow">${portalCopy[lang].portal}</p><h2>${portalCopy[lang].intro}</h2><p>${portalCopy[lang].inviteOnly}</p><a class="button gold" href="/portal/?lang=${lang}">${portalCopy[lang].login} →</a></section>
 ${intakeMarkup(c)}
 <section id="contact" class="contact"><div class="wrap contact-grid"><div><p class="eyebrow">${t.contactLabel}</p><h2>${t.contactTitle}</h2><p>${t.contactText}</p><div class="contact-links"><a href="tel:+353449348312"><small>${t.call}</small>+353 (0)44 934 8312 <span>↗</span></a><a href="mailto:reception@ndsol.ie"><small>${t.email}</small>reception@ndsol.ie <span>↗</span></a></div></div><div class="address-card"><span class="mini-mark">N&D</span><p class="eyebrow">${t.address}</p><h3>Nooney & Dowdall LLP</h3><address>16 Mary Street<br>Mullingar, Co. Westmeath<br>Ireland · N91 XY64</address><a class="button gold" href="https://www.google.com/maps/search/?api=1&query=Nooney+Dowdall+16+Mary+Street+Mullingar">${t.directions} ↗</a></div></div></section>
 <section class="gratitude wrap"><span class="gratitude-symbol" aria-hidden="true">✳</span><div><h2>${t.thanksTitle}</h2><p>${t.thanks}</p></div></section></main>
 <footer class="wrap"><div class="footer-top"><a class="footer-brand" href="#top">Nooney & Dowdall<small>LLP · SOLICITORS</small></a><a href="#top">${t.back} ↑</a></div><details class="privacy"><summary>${t.privacyTitle}</summary><p>${c.privacy}</p><a href="https://mullingarsolicitors.ie/privacy-policy/">${t.privacyLink} ↗</a><p>${t.translation}</p></details><div class="footer-bottom"><span>© 2026 · Vimaka Sistemas Inteligentes</span><span>${t.rights}</span></div></footer><a class="assistant-shortcut" href="#assistant">${c.label} ↗</a></body></html>`;
}
