import {readFileSync} from 'node:fs';
export const sourceSite=JSON.parse(readFileSync(new URL('./source/site.json',import.meta.url),'utf8'));
sourceSite.pages=sourceSite.pages.map(p=>JSON.parse(readFileSync(new URL('./source/'+p.file,import.meta.url),'utf8')));
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const friendly=s=>s.toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
export function fullMenu(){return `<nav class="full-menu" aria-label="Main navigation"><a href="/en-IE/">Home</a>${sourceSite.menu.map(item=>item.children.length?`<details><summary>${escape(friendly(item.label))}</summary><div class="menu-panel"><a class="menu-overview" href="${escape(item.href)}">${escape(friendly(item.label))} · Overview</a>${item.children.map(child=>`<a href="${escape(child.href)}">${escape(child.label)}</a>`).join('')}</div></details>`:`<a href="${escape(item.href)}">${escape(friendly(item.label))}</a>`).join('')}<a class="menu-portal" href="/portal/">Client area</a></nav>`;}
export function sourceFooter(){return `<div class="source-links"><a href="/en-IE/site-map/">All pages</a><a href="/en-IE/privacy-policy/">Original practice privacy policy</a><a href="/en-IE/cookie-policy/">Original practice cookie policy</a></div>`;}
function cards(pages){return `<div class="source-cards">${pages.map(p=>`<a href="/en-IE${p.path}"><span>${p.type==='posts'?'Article':'Page'}</span><h2>${escape(p.title)}</h2><b aria-hidden="true">↗</b></a>`).join('')}</div>`;}
export function renderSourcePages(shell){const output={};for(const p of sourceSite.pages){if(p.path==='/')continue;const policy=['/privacy-policy/','/cookie-policy/'].includes(p.path);let body=p.body;if(p.path==='/blog-articles/')body=cards(sourceSite.pages.filter(x=>x.type==='posts'));const notice=policy?'This is the original practice’s policy, reproduced as source material. It does not describe the independent project’s client portal or AI processing. See this website’s own privacy information and portal notices.':'Imported English content from the original practice website. This independent proposal is not an endorsement by the practice. Article dates and legal information have not been revalidated as current advice.';
const main=`<main id="main" class="source-main"><section class="source-heading wrap"><a href="/en-IE/">Home</a> <span aria-hidden="true">/</span> <a href="/en-IE/site-map/">All pages</a><p class="eyebrow">NOONEY &amp; DOWDALL LLP</p><h1>${escape(p.title)}</h1><p class="source-origin">Source updated ${escape(p.modified.split('T')[0])} · Imported ${sourceSite.fetchedAt} · <a href="${escape(p.url)}">Original page ↗</a></p></section><div class="wrap"><aside class="source-notice">${notice}</aside><article class="source-body">${body}</article><div class="source-next"><a class="button gold" href="/en-IE/contact-us/">Contact the practice ↗</a><a class="quiet" href="/portal/">Client area ↗</a></div></div></main>`;
output['/en-IE'+p.path]=shell.replace(/<title>[\s\S]*?<\/title>/,`<title>${escape(p.title)} · Nooney &amp; Dowdall</title>`).replace(/<meta name="description"[^>]*>/,'').replace(/<script src="\/app.js[^>]*><\/script>/,'').replace(/<main id="main">[\s\S]*?<\/main>/,main).replace('class="assistant-shortcut" href="#assistant"','class="assistant-shortcut" href="/en-IE/#assistant"');}
const index=output['/en-IE/blog-articles/'];output['/en-IE/category/uncategorized/']=index;const all=cards(sourceSite.pages.filter(p=>p.path!=='/'));output['/en-IE/site-map/']=index.replace(/<title>[\s\S]*?<\/title>/,'<title>All pages · Nooney &amp; Dowdall</title>').replace('<h1>BLOG ARTICLES</h1>','<h1>All pages</h1>').replace(/<p class="source-origin">[\s\S]*?<\/p>/,`<p class="source-origin">Original website content imported ${sourceSite.fetchedAt}</p>`).replace(/<article class="source-body">[\s\S]*?<\/article>/,`<article class="source-body">${all}</article>`);return output;}
